name: Build, Release, and Publish
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Compile TypeScript
        run: npm run compile
      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Check version matches package.json
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION="${{ steps.version.outputs.version }}"
          echo "Package version: $PACKAGE_VERSION"
          echo "Tag version: $TAG_VERSION"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Package version ($PACKAGE_VERSION) doesn't match tag version ($TAG_VERSION)"
            exit 1
          fi
          echo "Version check passed!"
      - name: Install vsce
        run: npm install -g @vscode/vsce@latest
      - name: Package extension
        run: vsce package
      - name: Create GitHub Release
        run: |
          gh release create v${{ steps.version.outputs.version }} \
            ./blobify-format-${{ steps.version.outputs.version }}.vsix \
            --title "Blobify Format v${{ steps.version.outputs.version }}" \
            --notes "## Changes in v${{ steps.version.outputs.version }}
          - See [CHANGELOG.md](./CHANGELOG.md) for details
          ## Installation
          Install from the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=ShentonConsulting.blobify-format)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to VS Code Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
